version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=/app/integrated_communication.db
      - EMAIL_SERVER=smtp
      - EMAIL_PORT=1025
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8080
    volumes:
      - ./:/app
    depends_on:
      - smtp

  smtp:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"